export const REQUEST_BOOKS = "REQUEST_BOOKS";
export const RECEIVE_BOOKS = "RECEIVE_BOOKS";
export const REQUEST_BOOK_INFO = "REQUEST_BOOK_INFO";
export const RECEIVE_BOOK_INFO = "RECEIVE_BOOK_INFO";

